# Form implementation generated from reading ui file 'projpt1.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ATM(object):
    def setupUi(self, ATM):
        ATM.setObjectName("ATM")
        ATM.resize(466, 604)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ATM.sizePolicy().hasHeightForWidth())
        ATM.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=ATM)
        self.centralwidget.setObjectName("centralwidget")
        self.Fname = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Fname.setEnabled(True)
        self.Fname.setGeometry(QtCore.QRect(50, 50, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fname.sizePolicy().hasHeightForWidth())
        self.Fname.setSizePolicy(sizePolicy)
        self.Fname.setAutoFillBackground(False)
        self.Fname.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Fname.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Fname.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.Fname.setLineWrapColumnOrWidth(1)
        self.Fname.setObjectName("Fname")
        self.Lname = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Lname.setGeometry(QtCore.QRect(50, 110, 101, 31))
        self.Lname.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Lname.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Lname.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.Lname.setObjectName("Lname")
        self.PIN = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.PIN.setGeometry(QtCore.QRect(50, 160, 101, 31))
        self.PIN.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PIN.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PIN.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.PIN.setObjectName("PIN")
        self.INFNAME = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.INFNAME.setGeometry(QtCore.QRect(180, 50, 241, 31))
        self.INFNAME.setObjectName("INFNAME")
        self.INLNAME = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.INLNAME.setGeometry(QtCore.QRect(180, 110, 241, 31))
        self.INLNAME.setObjectName("INLNAME")
        self.INPIN = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.INPIN.setGeometry(QtCore.QRect(180, 160, 241, 31))
        self.INPIN.setObjectName("INPIN")
        self.Withdraw = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Withdraw.setGeometry(QtCore.QRect(120, 370, 95, 20))
        self.Withdraw.setObjectName("Withdraw")
        self.Deposit = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Deposit.setGeometry(QtCore.QRect(270, 370, 95, 20))
        self.Deposit.setObjectName("Deposit")
        self.Ampunt = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Ampunt.setGeometry(QtCore.QRect(50, 440, 101, 31))
        self.Ampunt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Ampunt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.Ampunt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.Ampunt.setObjectName("Ampunt")
        self.INAMOUNT = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.INAMOUNT.setGeometry(QtCore.QRect(180, 440, 241, 31))
        self.INAMOUNT.setObjectName("INAMOUNT")
        self.Search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Search.setGeometry(QtCore.QRect(190, 240, 93, 28))
        self.Search.setObjectName("Search")
        self.Enter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(100, 510, 93, 28))
        self.Enter.setObjectName("Enter")
        self.Exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(280, 510, 93, 28))
        self.Exit.setObjectName("Exit")
        self.ATM_2 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.ATM_2.setEnabled(True)
        self.ATM_2.setGeometry(QtCore.QRect(200, 10, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ATM_2.sizePolicy().hasHeightForWidth())
        self.ATM_2.setSizePolicy(sizePolicy)
        self.ATM_2.setAutoFillBackground(False)
        self.ATM_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ATM_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ATM_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.ATM_2.setLineWrapColumnOrWidth(1)
        self.ATM_2.setObjectName("ATM_2")
        ATM.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ATM)
        self.statusbar.setObjectName("statusbar")
        ATM.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(parent=ATM)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 466, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuATM = QtWidgets.QMenu(parent=self.menuBar)
        self.menuATM.setObjectName("menuATM")
        ATM.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuATM.menuAction())

        self.retranslateUi(ATM)
        QtCore.QMetaObject.connectSlotsByName(ATM)

    def retranslateUi(self, ATM):
        _translate = QtCore.QCoreApplication.translate
        ATM.setWindowTitle(_translate("ATM", "MainWindow"))
        self.Fname.setHtml(_translate("ATM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\">First Name</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p></body></html>"))
        self.Lname.setHtml(_translate("ATM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\">Last Name</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p></body></html>"))
        self.PIN.setHtml(_translate("ATM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:9pt;\">Enter PIN</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p></body></html>"))
        self.Withdraw.setText(_translate("ATM", "Withdraw"))
        self.Deposit.setText(_translate("ATM", "Deposit"))
        self.Ampunt.setHtml(_translate("ATM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Amount</p></body></html>"))
        self.Search.setText(_translate("ATM", "SEARCH"))
        self.Enter.setText(_translate("ATM", "ENTER"))
        self.Exit.setText(_translate("ATM", "EXIT"))
        self.ATM_2.setHtml(_translate("ATM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ATM</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menuATM.setTitle(_translate("ATM", "ATM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ATM = QtWidgets.QMainWindow()
    ui = Ui_ATM()
    ui.setupUi(ATM)
    ATM.show()
    sys.exit(app.exec())
